## render.R -- generated by setup
## CI installs these R packages, then renders the whole quarto site.
## To add a package later: add its name to the pkgs vector and commit.
pkgs <- c("quarto", "knitr", "rmarkdown", "data.table", "DBI", "atime", "ggplot2", "curl", "duckdb")
installed <- rownames(installed.packages())
missing <- setdiff(pkgs, installed)
if (length(missing)) install.packages(missing)
quarto::quarto_render()
