## render.R -- generated by setup
## CI installs these R packages, then renders the whole quarto site.
## To add a package later: add its name to the pkgs vector and commit.
pkgs <- c("quarto", "knitr", "rmarkdown", "torch", "data.table")
installed <- rownames(installed.packages())
missing <- setdiff(pkgs, installed)
if (length(missing)) install.packages(missing)

if (!torch::torch_is_installed()) {
  torch::install_torch()
}
quarto::quarto_render()
